class Commands:
    LEECH = "leech4"
    PURGE = "dall4"
    PAUSEALL = "pall4"
    RESUMEALL = "rall4"
    STATUS = "status4"
    SETTINGS = "set4"
    EXEC = "cmd"
    UPLOAD = "upload"
    YTDL = "ytdl4"
    PYTDL = "pytdl4"
    ABOUT = "about4"
    GETLOGS = "log"
    SERVER = "server4"
    USERSETTINGS = "usetting4"
    INSTADL = "instadl4"
