class Commands:
    LEECH = "leech2"
    PURGE = "dall2"
    PAUSEALL = "pall2"
    RESUMEALL = "rall2"
    STATUS = "status2"
    SETTINGS = "set2"
    EXEC = "cmd"
    UPLOAD = "upload"
    YTDL = "ytdl2"
    PYTDL = "pytdl2"
    ABOUT = "about2"
    GETLOGS = "log"
    SERVER = "server2"
    USERSETTINGS = "usetting3"
    INSTADL = "instadl2"
