class Commands:
    LEECH = "leech3"
    PURGE = "dall3"
    PAUSEALL = "pall3"
    RESUMEALL = "rall3"
    STATUS = "status3"
    SETTINGS = "set3"
    EXEC = "cmd"
    UPLOAD = "upload"
    YTDL = "ytdl3"
    PYTDL = "pytdl3"
    ABOUT = "about3"
    GETLOGS = "log"
    SERVER = "server3"
    USERSETTINGS = "usetting3"
    INSTADL = "instadl3"
